version: '3.5'
services:
  slsapp:
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    stdin_open: true
    image: slspydev
    container_name: slspydev-c
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8000:8000"
      - "8001:8001"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
#    command: sls offline --host 0.0.0.0
